//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace JsonCompare.DiffService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CompareService", Namespace="http://schemas.hp.com/SM/7")]
    public partial class CompareService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RetrieveCompareServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveCompareServiceKeysListOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveCompareServiceListOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveCompareServiceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CompareService() {
            this.Url = global::JsonCompare.Properties.Settings.Default.JsonCompare_DiffService_CompareService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RetrieveCompareServiceCompletedEventHandler RetrieveCompareServiceCompleted;
        
        /// <remarks/>
        public event RetrieveCompareServiceKeysListCompletedEventHandler RetrieveCompareServiceKeysListCompleted;
        
        /// <remarks/>
        public event RetrieveCompareServiceListCompletedEventHandler RetrieveCompareServiceListCompleted;
        
        /// <remarks/>
        public event SaveCompareServiceCompletedEventHandler SaveCompareServiceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Retrieve", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RetrieveCompareServiceResponse", Namespace="http://schemas.hp.com/SM/7")]
        public RetrieveCompareServiceResponse RetrieveCompareService([System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.hp.com/SM/7")] RetrieveCompareServiceRequest RetrieveCompareServiceRequest) {
            object[] results = this.Invoke("RetrieveCompareService", new object[] {
                        RetrieveCompareServiceRequest});
            return ((RetrieveCompareServiceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void RetrieveCompareServiceAsync(RetrieveCompareServiceRequest RetrieveCompareServiceRequest) {
            this.RetrieveCompareServiceAsync(RetrieveCompareServiceRequest, null);
        }
        
        /// <remarks/>
        public void RetrieveCompareServiceAsync(RetrieveCompareServiceRequest RetrieveCompareServiceRequest, object userState) {
            if ((this.RetrieveCompareServiceOperationCompleted == null)) {
                this.RetrieveCompareServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveCompareServiceOperationCompleted);
            }
            this.InvokeAsync("RetrieveCompareService", new object[] {
                        RetrieveCompareServiceRequest}, this.RetrieveCompareServiceOperationCompleted, userState);
        }
        
        private void OnRetrieveCompareServiceOperationCompleted(object arg) {
            if ((this.RetrieveCompareServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveCompareServiceCompleted(this, new RetrieveCompareServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RetrieveKeysList", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RetrieveCompareServiceKeysListResponse", Namespace="http://schemas.hp.com/SM/7")]
        public RetrieveCompareServiceKeysListResponse RetrieveCompareServiceKeysList([System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.hp.com/SM/7")] RetrieveCompareServiceKeysListRequest RetrieveCompareServiceKeysListRequest) {
            object[] results = this.Invoke("RetrieveCompareServiceKeysList", new object[] {
                        RetrieveCompareServiceKeysListRequest});
            return ((RetrieveCompareServiceKeysListResponse)(results[0]));
        }
        
        /// <remarks/>
        public void RetrieveCompareServiceKeysListAsync(RetrieveCompareServiceKeysListRequest RetrieveCompareServiceKeysListRequest) {
            this.RetrieveCompareServiceKeysListAsync(RetrieveCompareServiceKeysListRequest, null);
        }
        
        /// <remarks/>
        public void RetrieveCompareServiceKeysListAsync(RetrieveCompareServiceKeysListRequest RetrieveCompareServiceKeysListRequest, object userState) {
            if ((this.RetrieveCompareServiceKeysListOperationCompleted == null)) {
                this.RetrieveCompareServiceKeysListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveCompareServiceKeysListOperationCompleted);
            }
            this.InvokeAsync("RetrieveCompareServiceKeysList", new object[] {
                        RetrieveCompareServiceKeysListRequest}, this.RetrieveCompareServiceKeysListOperationCompleted, userState);
        }
        
        private void OnRetrieveCompareServiceKeysListOperationCompleted(object arg) {
            if ((this.RetrieveCompareServiceKeysListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveCompareServiceKeysListCompleted(this, new RetrieveCompareServiceKeysListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RetrieveList", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RetrieveCompareServiceListResponse", Namespace="http://schemas.hp.com/SM/7")]
        public RetrieveCompareServiceListResponse RetrieveCompareServiceList([System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.hp.com/SM/7")] RetrieveCompareServiceListRequest RetrieveCompareServiceListRequest) {
            object[] results = this.Invoke("RetrieveCompareServiceList", new object[] {
                        RetrieveCompareServiceListRequest});
            return ((RetrieveCompareServiceListResponse)(results[0]));
        }
        
        /// <remarks/>
        public void RetrieveCompareServiceListAsync(RetrieveCompareServiceListRequest RetrieveCompareServiceListRequest) {
            this.RetrieveCompareServiceListAsync(RetrieveCompareServiceListRequest, null);
        }
        
        /// <remarks/>
        public void RetrieveCompareServiceListAsync(RetrieveCompareServiceListRequest RetrieveCompareServiceListRequest, object userState) {
            if ((this.RetrieveCompareServiceListOperationCompleted == null)) {
                this.RetrieveCompareServiceListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveCompareServiceListOperationCompleted);
            }
            this.InvokeAsync("RetrieveCompareServiceList", new object[] {
                        RetrieveCompareServiceListRequest}, this.RetrieveCompareServiceListOperationCompleted, userState);
        }
        
        private void OnRetrieveCompareServiceListOperationCompleted(object arg) {
            if ((this.RetrieveCompareServiceListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveCompareServiceListCompleted(this, new RetrieveCompareServiceListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Save", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("SaveCompareServiceResponse", Namespace="http://schemas.hp.com/SM/7")]
        public SaveCompareServiceResponse SaveCompareService([System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.hp.com/SM/7")] SaveCompareServiceRequest SaveCompareServiceRequest) {
            object[] results = this.Invoke("SaveCompareService", new object[] {
                        SaveCompareServiceRequest});
            return ((SaveCompareServiceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SaveCompareServiceAsync(SaveCompareServiceRequest SaveCompareServiceRequest) {
            this.SaveCompareServiceAsync(SaveCompareServiceRequest, null);
        }
        
        /// <remarks/>
        public void SaveCompareServiceAsync(SaveCompareServiceRequest SaveCompareServiceRequest, object userState) {
            if ((this.SaveCompareServiceOperationCompleted == null)) {
                this.SaveCompareServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveCompareServiceOperationCompleted);
            }
            this.InvokeAsync("SaveCompareService", new object[] {
                        SaveCompareServiceRequest}, this.SaveCompareServiceOperationCompleted, userState);
        }
        
        private void OnSaveCompareServiceOperationCompleted(object arg) {
            if ((this.SaveCompareServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveCompareServiceCompleted(this, new SaveCompareServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.hp.com/SM/7")]
    public partial class RetrieveCompareServiceRequest {
        
        private CompareServiceModelType modelField;
        
        private bool attachmentInfoField;
        
        private bool attachmentInfoFieldSpecified;
        
        private bool attachmentDataField;
        
        private bool attachmentDataFieldSpecified;
        
        private bool ignoreEmptyElementsField;
        
        private bool updatecounterField;
        
        private bool updatecounterFieldSpecified;
        
        private string handleField;
        
        private long countField;
        
        private bool countFieldSpecified;
        
        private long startField;
        
        private bool startFieldSpecified;
        
        public RetrieveCompareServiceRequest() {
            this.ignoreEmptyElementsField = true;
        }
        
        /// <remarks/>
        public CompareServiceModelType model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool attachmentInfo {
            get {
                return this.attachmentInfoField;
            }
            set {
                this.attachmentInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentInfoSpecified {
            get {
                return this.attachmentInfoFieldSpecified;
            }
            set {
                this.attachmentInfoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool attachmentData {
            get {
                return this.attachmentDataField;
            }
            set {
                this.attachmentDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentDataSpecified {
            get {
                return this.attachmentDataFieldSpecified;
            }
            set {
                this.attachmentDataFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool ignoreEmptyElements {
            get {
                return this.ignoreEmptyElementsField;
            }
            set {
                this.ignoreEmptyElementsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool updatecounter {
            get {
                return this.updatecounterField;
            }
            set {
                this.updatecounterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updatecounterSpecified {
            get {
                return this.updatecounterFieldSpecified;
            }
            set {
                this.updatecounterFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string handle {
            get {
                return this.handleField;
            }
            set {
                this.handleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.hp.com/SM/7")]
    public partial class CompareServiceModelType {
        
        private CompareServiceKeysType keysField;
        
        private CompareServiceInstanceType instanceField;
        
        private MessageType[] messagesField;
        
        private string queryField;
        
        /// <remarks/>
        public CompareServiceKeysType keys {
            get {
                return this.keysField;
            }
            set {
                this.keysField = value;
            }
        }
        
        /// <remarks/>
        public CompareServiceInstanceType instance {
            get {
                return this.instanceField;
            }
            set {
                this.instanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("message", Namespace="http://schemas.hp.com/SM/7/Common", IsNullable=false)]
        public MessageType[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.hp.com/SM/7")]
    public partial class CompareServiceKeysType {
        
        private StringType nameField;
        
        private string queryField;
        
        private long updatecounterField;
        
        private bool updatecounterFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public StringType Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long updatecounter {
            get {
                return this.updatecounterField;
            }
            set {
                this.updatecounterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updatecounterSpecified {
            get {
                return this.updatecounterFieldSpecified;
            }
            set {
                this.updatecounterFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MessageType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.hp.com/SM/7/Common")]
    public partial class StringType {
        
        private string typeField;
        
        private bool mandatoryField;
        
        private bool mandatoryFieldSpecified;
        
        private bool readonlyField;
        
        private bool readonlyFieldSpecified;
        
        private string valueField;
        
        public StringType() {
            this.typeField = "String";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool mandatory {
            get {
                return this.mandatoryField;
            }
            set {
                this.mandatoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mandatorySpecified {
            get {
                return this.mandatoryFieldSpecified;
            }
            set {
                this.mandatoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool @readonly {
            get {
                return this.readonlyField;
            }
            set {
                this.readonlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool readonlySpecified {
            get {
                return this.readonlyFieldSpecified;
            }
            set {
                this.readonlyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.hp.com/SM/7/Common")]
    public partial class AttachmentType {
        
        private string contentTypeField;
        
        private string hrefField;
        
        private string contentIdField;
        
        private string actionField;
        
        private string nameField;
        
        private string typeField;
        
        private int lenField;
        
        private bool lenFieldSpecified;
        
        private string charsetField;
        
        private string uploadbyField;
        
        private string uploaddateField;
        
        private string attachmentTypeField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/2005/05/xmlmime")]
        public string contentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string contentId {
            get {
                return this.contentIdField;
            }
            set {
                this.contentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int len {
            get {
                return this.lenField;
            }
            set {
                this.lenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lenSpecified {
            get {
                return this.lenFieldSpecified;
            }
            set {
                this.lenFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string charset {
            get {
                return this.charsetField;
            }
            set {
                this.charsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("upload.by")]
        public string uploadby {
            get {
                return this.uploadbyField;
            }
            set {
                this.uploadbyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("upload.date")]
        public string uploaddate {
            get {
                return this.uploaddateField;
            }
            set {
                this.uploaddateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string attachmentType {
            get {
                return this.attachmentTypeField;
            }
            set {
                this.attachmentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.hp.com/SM/7")]
    public partial class CompareServiceInstanceType {
        
        private StringType nameField;
        
        private StringType contentField;
        
        private StringType queryStringField;
        
        private AttachmentType[] attachmentsField;
        
        private string queryField;
        
        private string uniquequeryField;
        
        private string recordidField;
        
        private long updatecounterField;
        
        private bool updatecounterFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public StringType Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public StringType Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public StringType QueryString {
            get {
                return this.queryStringField;
            }
            set {
                this.queryStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("attachment", Namespace="http://schemas.hp.com/SM/7/Common", IsNullable=false)]
        public AttachmentType[] attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uniquequery {
            get {
                return this.uniquequeryField;
            }
            set {
                this.uniquequeryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string recordid {
            get {
                return this.recordidField;
            }
            set {
                this.recordidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long updatecounter {
            get {
                return this.updatecounterField;
            }
            set {
                this.updatecounterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updatecounterSpecified {
            get {
                return this.updatecounterFieldSpecified;
            }
            set {
                this.updatecounterFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.hp.com/SM/7/Common")]
    public partial class MessageType : StringType {
        
        private int severityField;
        
        private bool severityFieldSpecified;
        
        private string moduleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool severitySpecified {
            get {
                return this.severityFieldSpecified;
            }
            set {
                this.severityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string module {
            get {
                return this.moduleField;
            }
            set {
                this.moduleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.hp.com/SM/7")]
    public partial class RetrieveCompareServiceResponse {
        
        private CompareServiceModelType modelField;
        
        private MessageType[] messagesField;
        
        private StatusType statusField;
        
        private string messageField;
        
        private System.DateTime schemaRevisionDateField;
        
        private int schemaRevisionLevelField;
        
        private decimal returnCodeField;
        
        private bool returnCodeFieldSpecified;
        
        private string queryField;
        
        private string handleField;
        
        private long countField;
        
        private bool countFieldSpecified;
        
        private bool moreField;
        
        private bool moreFieldSpecified;
        
        private long startField;
        
        private bool startFieldSpecified;
        
        /// <remarks/>
        public CompareServiceModelType model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("message", Namespace="http://schemas.hp.com/SM/7/Common", IsNullable=false)]
        public MessageType[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public StatusType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime schemaRevisionDate {
            get {
                return this.schemaRevisionDateField;
            }
            set {
                this.schemaRevisionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int schemaRevisionLevel {
            get {
                return this.schemaRevisionLevelField;
            }
            set {
                this.schemaRevisionLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnCodeSpecified {
            get {
                return this.returnCodeFieldSpecified;
            }
            set {
                this.returnCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string handle {
            get {
                return this.handleField;
            }
            set {
                this.handleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool more {
            get {
                return this.moreField;
            }
            set {
                this.moreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool moreSpecified {
            get {
                return this.moreFieldSpecified;
            }
            set {
                this.moreFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.hp.com/SM/7/Common")]
    public enum StatusType {
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        FAILURE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.hp.com/SM/7")]
    public partial class RetrieveCompareServiceKeysListRequest {
        
        private CompareServiceModelType modelField;
        
        private bool attachmentInfoField;
        
        private bool attachmentInfoFieldSpecified;
        
        private bool attachmentDataField;
        
        private bool attachmentDataFieldSpecified;
        
        private bool ignoreEmptyElementsField;
        
        private bool updatecounterField;
        
        private bool updatecounterFieldSpecified;
        
        private string handleField;
        
        private long countField;
        
        private bool countFieldSpecified;
        
        private long startField;
        
        private bool startFieldSpecified;
        
        public RetrieveCompareServiceKeysListRequest() {
            this.ignoreEmptyElementsField = true;
        }
        
        /// <remarks/>
        public CompareServiceModelType model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool attachmentInfo {
            get {
                return this.attachmentInfoField;
            }
            set {
                this.attachmentInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentInfoSpecified {
            get {
                return this.attachmentInfoFieldSpecified;
            }
            set {
                this.attachmentInfoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool attachmentData {
            get {
                return this.attachmentDataField;
            }
            set {
                this.attachmentDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentDataSpecified {
            get {
                return this.attachmentDataFieldSpecified;
            }
            set {
                this.attachmentDataFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool ignoreEmptyElements {
            get {
                return this.ignoreEmptyElementsField;
            }
            set {
                this.ignoreEmptyElementsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool updatecounter {
            get {
                return this.updatecounterField;
            }
            set {
                this.updatecounterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updatecounterSpecified {
            get {
                return this.updatecounterFieldSpecified;
            }
            set {
                this.updatecounterFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string handle {
            get {
                return this.handleField;
            }
            set {
                this.handleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.hp.com/SM/7")]
    public partial class RetrieveCompareServiceKeysListResponse {
        
        private CompareServiceKeysType[] keysField;
        
        private MessageType[] messagesField;
        
        private StatusType statusField;
        
        private string messageField;
        
        private System.DateTime schemaRevisionDateField;
        
        private int schemaRevisionLevelField;
        
        private decimal returnCodeField;
        
        private bool returnCodeFieldSpecified;
        
        private string queryField;
        
        private string handleField;
        
        private long countField;
        
        private bool countFieldSpecified;
        
        private bool moreField;
        
        private bool moreFieldSpecified;
        
        private long startField;
        
        private bool startFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("keys")]
        public CompareServiceKeysType[] keys {
            get {
                return this.keysField;
            }
            set {
                this.keysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("message", Namespace="http://schemas.hp.com/SM/7/Common", IsNullable=false)]
        public MessageType[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public StatusType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime schemaRevisionDate {
            get {
                return this.schemaRevisionDateField;
            }
            set {
                this.schemaRevisionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int schemaRevisionLevel {
            get {
                return this.schemaRevisionLevelField;
            }
            set {
                this.schemaRevisionLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnCodeSpecified {
            get {
                return this.returnCodeFieldSpecified;
            }
            set {
                this.returnCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string handle {
            get {
                return this.handleField;
            }
            set {
                this.handleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool more {
            get {
                return this.moreField;
            }
            set {
                this.moreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool moreSpecified {
            get {
                return this.moreFieldSpecified;
            }
            set {
                this.moreFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.hp.com/SM/7")]
    public partial class RetrieveCompareServiceListRequest {
        
        private CompareServiceKeysType[] keysField;
        
        private bool attachmentInfoField;
        
        private bool attachmentInfoFieldSpecified;
        
        private bool attachmentDataField;
        
        private bool attachmentDataFieldSpecified;
        
        private bool ignoreEmptyElementsField;
        
        private bool updatecounterField;
        
        private bool updatecounterFieldSpecified;
        
        private string handleField;
        
        private long countField;
        
        private bool countFieldSpecified;
        
        private long startField;
        
        private bool startFieldSpecified;
        
        private long attachmentTypeField;
        
        private bool attachmentTypeFieldSpecified;
        
        public RetrieveCompareServiceListRequest() {
            this.ignoreEmptyElementsField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("keys")]
        public CompareServiceKeysType[] keys {
            get {
                return this.keysField;
            }
            set {
                this.keysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool attachmentInfo {
            get {
                return this.attachmentInfoField;
            }
            set {
                this.attachmentInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentInfoSpecified {
            get {
                return this.attachmentInfoFieldSpecified;
            }
            set {
                this.attachmentInfoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool attachmentData {
            get {
                return this.attachmentDataField;
            }
            set {
                this.attachmentDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentDataSpecified {
            get {
                return this.attachmentDataFieldSpecified;
            }
            set {
                this.attachmentDataFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool ignoreEmptyElements {
            get {
                return this.ignoreEmptyElementsField;
            }
            set {
                this.ignoreEmptyElementsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool updatecounter {
            get {
                return this.updatecounterField;
            }
            set {
                this.updatecounterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updatecounterSpecified {
            get {
                return this.updatecounterFieldSpecified;
            }
            set {
                this.updatecounterFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string handle {
            get {
                return this.handleField;
            }
            set {
                this.handleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long attachmentType {
            get {
                return this.attachmentTypeField;
            }
            set {
                this.attachmentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentTypeSpecified {
            get {
                return this.attachmentTypeFieldSpecified;
            }
            set {
                this.attachmentTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.hp.com/SM/7")]
    public partial class RetrieveCompareServiceListResponse {
        
        private CompareServiceInstanceType[] instanceField;
        
        private MessageType[] messagesField;
        
        private StatusType statusField;
        
        private string messageField;
        
        private System.DateTime schemaRevisionDateField;
        
        private int schemaRevisionLevelField;
        
        private decimal returnCodeField;
        
        private bool returnCodeFieldSpecified;
        
        private string queryField;
        
        private string handleField;
        
        private long countField;
        
        private bool countFieldSpecified;
        
        private bool moreField;
        
        private bool moreFieldSpecified;
        
        private long startField;
        
        private bool startFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("instance")]
        public CompareServiceInstanceType[] instance {
            get {
                return this.instanceField;
            }
            set {
                this.instanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("message", Namespace="http://schemas.hp.com/SM/7/Common", IsNullable=false)]
        public MessageType[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public StatusType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime schemaRevisionDate {
            get {
                return this.schemaRevisionDateField;
            }
            set {
                this.schemaRevisionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int schemaRevisionLevel {
            get {
                return this.schemaRevisionLevelField;
            }
            set {
                this.schemaRevisionLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnCodeSpecified {
            get {
                return this.returnCodeFieldSpecified;
            }
            set {
                this.returnCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string handle {
            get {
                return this.handleField;
            }
            set {
                this.handleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool more {
            get {
                return this.moreField;
            }
            set {
                this.moreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool moreSpecified {
            get {
                return this.moreFieldSpecified;
            }
            set {
                this.moreFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.hp.com/SM/7")]
    public partial class SaveCompareServiceRequest {
        
        private CompareServiceModelType modelField;
        
        private bool attachmentInfoField;
        
        private bool attachmentInfoFieldSpecified;
        
        private bool attachmentDataField;
        
        private bool attachmentDataFieldSpecified;
        
        private bool ignoreEmptyElementsField;
        
        private long updateconstraintField;
        
        public SaveCompareServiceRequest() {
            this.ignoreEmptyElementsField = true;
            this.updateconstraintField = ((long)(-1));
        }
        
        /// <remarks/>
        public CompareServiceModelType model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool attachmentInfo {
            get {
                return this.attachmentInfoField;
            }
            set {
                this.attachmentInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentInfoSpecified {
            get {
                return this.attachmentInfoFieldSpecified;
            }
            set {
                this.attachmentInfoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool attachmentData {
            get {
                return this.attachmentDataField;
            }
            set {
                this.attachmentDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentDataSpecified {
            get {
                return this.attachmentDataFieldSpecified;
            }
            set {
                this.attachmentDataFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool ignoreEmptyElements {
            get {
                return this.ignoreEmptyElementsField;
            }
            set {
                this.ignoreEmptyElementsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "-1")]
        public long updateconstraint {
            get {
                return this.updateconstraintField;
            }
            set {
                this.updateconstraintField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.hp.com/SM/7")]
    public partial class SaveCompareServiceResponse {
        
        private CompareServiceModelType modelField;
        
        private MessageType[] messagesField;
        
        private StatusType statusField;
        
        private string messageField;
        
        private System.DateTime schemaRevisionDateField;
        
        private int schemaRevisionLevelField;
        
        private decimal returnCodeField;
        
        private bool returnCodeFieldSpecified;
        
        private string queryField;
        
        /// <remarks/>
        public CompareServiceModelType model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("message", Namespace="http://schemas.hp.com/SM/7/Common", IsNullable=false)]
        public MessageType[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public StatusType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime schemaRevisionDate {
            get {
                return this.schemaRevisionDateField;
            }
            set {
                this.schemaRevisionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int schemaRevisionLevel {
            get {
                return this.schemaRevisionLevelField;
            }
            set {
                this.schemaRevisionLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnCodeSpecified {
            get {
                return this.returnCodeFieldSpecified;
            }
            set {
                this.returnCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void RetrieveCompareServiceCompletedEventHandler(object sender, RetrieveCompareServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveCompareServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveCompareServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RetrieveCompareServiceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RetrieveCompareServiceResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void RetrieveCompareServiceKeysListCompletedEventHandler(object sender, RetrieveCompareServiceKeysListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveCompareServiceKeysListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveCompareServiceKeysListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RetrieveCompareServiceKeysListResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RetrieveCompareServiceKeysListResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void RetrieveCompareServiceListCompletedEventHandler(object sender, RetrieveCompareServiceListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveCompareServiceListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveCompareServiceListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RetrieveCompareServiceListResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RetrieveCompareServiceListResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SaveCompareServiceCompletedEventHandler(object sender, SaveCompareServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveCompareServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveCompareServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SaveCompareServiceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SaveCompareServiceResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591